### ISSUE TITLE
Doesn't let me download mod

### ISSUE THREAD

**Issue by Infernogd** [wlagos3/edit-attempts#1]
Hi when I was going to download the mod but  it gave me this
![image](https://github.com/user-attachments/assets/a791b66d-74b7-425f-8641-88bf7e263346)
please fix thanks :)

**Comment by wlagos3** [comment]
Why did you go through so much trouble to find this repo

**Comment by wlagos3** [comment]
It will be fixed

**Comment by InfernoZv** [comment]
I tried to find your discord to dm you but I couldn't find it at all 😭
